version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: gaston
      MONGO_INITDB_ROOT_PASSWORD: 5YIgYbr5AsLUb9OA
    ports:
      - 27017:27017
    volumes:
     - ./mongo_data:/data/db